Code Review for [add-associations] | Library Manager Project
luigirazum/library-manager pull request #3
Opened 2023-07-27 11:42 UTC by luigirazum

# Hello Dear Code Reviewers Team 👋,
## I would like to ask for your kindly help to do the 🔍 Code Review 👀 for my project.
### The following requirements 📌 were fulfilled this time:
#### - 🎯 General requirements
- 📌 Make sure that there are no linter errors.
  - ✅ Linters for Ruby were installed. `Rubocop` reported no errors.
- 📌 Make sure that you used the correct GitFlow.
  - ✅ `add-associations` feature branch was created from `dev` to follow the `git-flow`.
- 📌 Make sure that you documented your work in a professional way.
  - ✅ `README` file was updated with all the Project 3/7 details.
#### - 🎯 Ruby requirements
- 📌 Follow the list of best practices for Ruby.
  - ✅ Best practices for `Ruby` were followed.
#### - 🎯 Project requirements
Create the remaining <kbd>Classes</kbd> for our **Ruby School Library App** and create the <kbd>Associations</kbd> between them.
- 📌 Create a class <kbd>Classroom</kbd> with the following:
  - ✅ `@label` instance variable, should be initialized in the constructor.
  - ✅ Setter and getter for `@label` (remember about `attr_accessor`).
- 📌 Create the `has-many`/`belongs-to` relationship between <kbd>Classroom</kbd> and <kbd>Student</kbd>.
The following should be implemented:
  - ✅ Create the `has-many` side (a <kbd>Classroom</kbd> has many <kbd>Student</kbd>s).
  - ✅ Create the `belongs-to` side (a <kbd>Student</kbd> belongs to a <kbd>Classroom</kbd>).
  - ✅ Make sure that when adding a <kbd>Student</kbd> to a <kbd>Classroom</kbd> it also sets the <kbd>Classroom</kbd> for the <kbd>Student</kbd>.
  - ✅ Make sure that when setting the <kbd>Classroom</kbd> for a <kbd>Student</kbd> it also adds it to the <kbd>Classroom</kbd>s' <kbd>Student</kbd>s.
- 📌 Create a class <kbd>Book</kbd> with the following:
  - ✅ `@title` and `@author` instance variables, should be initialized in the constructor.
  - ✅ Setters and getters for instance variables (remember about `attr_accessor`).
- 📌 Create a class <kbd>Rental</kbd> with the following:
  - ✅ `@date` instance variable, should be initialized in the constructor.
  - ✅ Setter and getter for `@date` (remember about `attr_accessor`).
- 📌 Create the `many-to-many` (also `has-many-through`) relationship between <kbd>Person</kbd> and <kbd>Book</kbd> using the intermediate class <kbd>Rental</kbd>.
The following should be implemented:
  - ✅ Create the `has-many` side of <kbd>Book</kbd> and <kbd>Rental</kbd> (a <kbd>Book</kbd> has many <kbd>Rental</kbd>s).
  - ✅ Create the `belongs-to` side of <kbd>Rental</kbd> and <kbd>Book</kbd> (a <kbd>Rental</kbd> belongs to a <kbd>Book</kbd>).
  - ✅ Create the `has-many` side of <kbd>Person</kbd> and <kbd>Rental</kbd> (a <kbd>Person</kbd> has many <kbd>Rental</kbd>s).
  - ✅ Create the `belongs-to` side of <kbd>Rental</kbd> and <kbd>Person</kbd> (a <kbd>Rental</kbd> belongs to a <kbd>Person</kbd>).
  - ✅ Modify the constructor of <kbd>Rental</kbd> so <kbd>Book</kbd> and <kbd>Person</kbd> are set in it.
- 📌 See the <kbd>Associations</kbd> in action
    - ✅ A 'main.rb' was created on the 'root' folder, you can run it with `>ruby main.rb` to see how the associations work.

  ```ruby
  # a chemistry classroom is created
  chemistry = Classroom.new('chemistry')

  # a student is created, he is in chemistry classroom
  student = Student.new(22, chemistry, 'maximilianus')

  # a book1 is created, it hasn't been rented
  book1 = Book.new('chemistry for nubbies', 'ruth green')

  # a book2 is created, it hasn't been rented
  book2 = Book.new('chemistry advanced', 'john fitzgerald')

  # a teacher is created, with chemistry specialization
  teacher = Teacher.new(22, 'chemistry', 'mr. smith')

  # teacher rents book1 on may 25, 2023
  teacher.add_rental('05/25/2023', book1)

  # book2 is rented by student on may 25, 2023
  book2.add_rental('05/25/2023', student)
  ```

  The result of the previous code once you ran it should be:
  ```irb
  ❯ ruby main.rb
  ---- create a classroom ---
  classroom: chemistry
  classroom students: []
  
  ---- create a student ---
  student: maximilianus
  student classroom: chemistry
  student rentals: []

  ...
  ...
  ```

### I really thank you for your support. 🙏
### Cheers and Happy Reviewing! 👀
### Luis 🙋‍♂️

2023-07-27 21:07 UTC, Felix45 requested changes
Hi @luigirazum, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Most of the class associations have been setup correctly :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 21:07 UTC, Felix45 commented on classes/student.rb
> +    @classroom.students << self unless @classroom.students.include?(self)
- [ Required ] I think it would be better to factor out this part of your code into a standalone `setter` method as specified in the project requirements. Setting the classroom of a student only in the constructor makes it impossible for someone to update the classroom of the student after the `instance` of the class has been created. If you create a setter method for setting the classroom, then the classroom attribute can be updated even after the `instance` of the class has been created. I would like to suggest that you refactor your code as shown below.

## Example code
> I think according to the project requirements the classroom attribute should be read-only and the only way to set it should be through the setter method as shown below, so that when setting the classroom for a student it also adds it to the classrooms' students.

```ruby
require_relative 'person'

class Student < Person
  attr_reader :classroom

  def initialize(age, name, parent_permission)
    super(age, name, parent_permission: parent_permission)
  end

  def play_hooky
    '¯\(ツ)/¯'
  end

  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
end
```

## Project requirements
![Screenshot from 2023-07-27 23-54-32](https://github.com/luigirazum/library-manager/assets/16392046/dcd739ed-04b3-4eb4-a03f-dfd065dabd1d)

2023-07-27 23:04 UTC, luigirazum commented on classes/student.rb
> +    @classroom.students << self unless @classroom.students.include?(self)
Thanks for your feedback @Felix45.
I will implement the required changes.

2023-07-27 23:11 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi @luigirazum 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Set up associations between classes and objects.
- ✔️ Meaningful commit messages.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 00:48 UTC, luigirazum commented
Thanks for your feedback @abdulhamiid.

2023-07-28 00:48 UTC, merged